// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmeqNHLj5esptdolv2swdPu4jnfZ8OjDo',
    appId: '1:833044383460:web:27c83956c7da640e104ef1',
    messagingSenderId: '833044383460',
    projectId: 'my-chaat',
    authDomain: 'my-chaat.firebaseapp.com',
    storageBucket: 'my-chaat.appspot.com',
    measurementId: 'G-H1E29ENYPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdyaJeYm2iPrLS8aAm0dXMQEFX87IZR0',
    appId: '1:833044383460:android:6f929872f7b1f6fa104ef1',
    messagingSenderId: '833044383460',
    projectId: 'my-chaat',
    storageBucket: 'my-chaat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgm1c1y_2YkGsc7Y2AqTUIz1nCrqcycC8',
    appId: '1:833044383460:ios:e57c410122f7ba9c104ef1',
    messagingSenderId: '833044383460',
    projectId: 'my-chaat',
    storageBucket: 'my-chaat.appspot.com',
    iosBundleId: 'com.example.myyyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgm1c1y_2YkGsc7Y2AqTUIz1nCrqcycC8',
    appId: '1:833044383460:ios:1befe6a1e114f16e104ef1',
    messagingSenderId: '833044383460',
    projectId: 'my-chaat',
    storageBucket: 'my-chaat.appspot.com',
    iosBundleId: 'com.example.myyyy.RunnerTests',
  );
}
